<?php

/** @noinspection PhpArgumentWithoutNamedIdentifierInspection */

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

namespace Resursbankabpayments\Woocommerce\Modules\GetAddress\Filter;

use Resursbank\Ecom\Exception\FilesystemException;
use Resursbank\Ecom\Exception\HttpException;
use Resursbank\Ecom\Exception\Validation\EmptyValueException;
use Resursbank\Ecom\Exception\Validation\IllegalValueException;
use Resursbank\Ecom\Module\Widget\CostList\Css as CostListCss;
use Resursbank\Ecom\Module\Widget\CostList\Js as CostListJs;
use Resursbank\Ecom\Module\Widget\PartPayment\Css as EcomPartPaymentCss;
use Resursbank\Ecom\Module\Widget\ReadMore\Css as ReadMoreCss;
use Resursbank\Ecom\Module\Widget\ReadMore\Js as ReadMoreJs;
use Resursbankabpayments\Woocommerce\Database\Options\Advanced\EnableGetAddress;
use Resursbankabpayments\Woocommerce\Database\Options\Advanced\LogLevel;
use Resursbankabpayments\Woocommerce\Modules\GetAddress\GetAddress;
use Resursbankabpayments\Woocommerce\Modules\PartPayment\PartPayment;
use Resursbankabpayments\Woocommerce\Util\Log;
use Resursbankabpayments\Woocommerce\Util\ResourceType;
use Resursbankabpayments\Woocommerce\Util\Route;
use Resursbankabpayments\Woocommerce\Util\Url;
use Resursbankabpayments\Woocommerce\Util\WcSession;
use Resursbankabpayments\Woocommerce\Util\WooCommerce;
use Throwable;

/**
 * Queue CSS & JS for the get address widget in frontend checkout. Do not call directly, use WP queues.
 */
class AssetLoader
{
    /**
     * Enqueued script execution.
     *
     * @throws EmptyValueException
     * @throws FilesystemException
     * @throws HttpException
     * @throws IllegalValueException
     */
    public static function init(): void
    {
        // Things that have to be loaded regardless.
        self::enqueueCostListStyle();
        self::enqueueCostListJs();
        self::enqueuePartPaymentStyles();
        self::enqueueReadMoreStyle();
        self::enqueueReadMoreJs();

        if (!is_checkout()) {
            return;
        }

        self::enqueueBasicGetAddressStyle();
        self::enqueueGetAddressJs();
    }

    /**
     * @noinspection PhpArgumentWithoutNamedIdentifierInspection
     */
    public static function enqueueCostListStyle(): void
    {
        wp_register_style('resursbankabpaygw-costlist-css', false, [], '1.0.0');
        wp_enqueue_style('resursbankabpaygw-costlist-css');

        $costListCssSafe = (string) (new CostListCss())->content;

        if ($costListCssSafe === '') {
            return;
        }

        /*
         * Trusted SDK payload.
         * This content is generated by the Resurs Bank SDK as CSS and must remain valid CSS.
         * There is no general esc_*() helper for full stylesheet blocks in wp_add_inline_style().
         * safecss_filter_attr() is for style attributes, not full CSS blocks.
         */
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe CSS payload from trusted SDK, escaped at source by contract.
        wp_add_inline_style('resursbankabpaygw-costlist-css', esc_html(wp_strip_all_tags($costListCssSafe)));
    }

    /**
     * Enqueue scripts related to CostList.
     *
     * @noinspection PhpArgumentWithoutNamedIdentifierInspection
     */
    public static function enqueueCostListJs(): void
    {
        $costListJsSafe = (string) (new CostListJs(containerElDomPath: 'body'))->content;

        wp_register_script(
            'resursbankabpaygw-costlist-js',
            '',
            ['wc-blocks-data-store'],
            '1.0.0',
            true
        );
        wp_enqueue_script('resursbankabpaygw-costlist-js');

        if ($costListJsSafe === '') {
            return;
        }

        /*
         * Trusted SDK payload.
         * This content is generated by the Resurs Bank SDK and must remain executable JS.
         * It cannot be passed through esc_js() or wp_kses() without breaking the script.
         * Per WordPress escaping guidance, this is treated as a safe prebuilt payload.
         */
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe JS payload from trusted SDK, escaped at source by contract.
        wp_add_inline_script('resursbankabpaygw-costlist-js', $costListJsSafe);
    }

    public static function enqueuePartPaymentStyles(): void
    {
        try {
            $cssSafe = (string) ((new EcomPartPaymentCss())->content ?? '');
        } catch (Throwable $error) {
            Log::error(error: $error);
            $cssSafe = '';
        }

        wp_register_style('resursbankabpaygw-pp-styles', false, [], '1.0.0');
        wp_enqueue_style('resursbankabpaygw-pp-styles');

        if ($cssSafe !== '') {
            /*
             * Trusted SDK payload.
             * This content is generated by the Resurs Bank SDK as CSS and must remain valid CSS.
             * There is no general esc_*() helper for full stylesheet blocks in wp_add_inline_style().
             * safecss_filter_attr() is for style attributes, not full CSS blocks.
             */
            // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe CSS payload from trusted SDK, escaped at source by contract.
            wp_add_inline_style('resursbankabpaygw-pp-styles', $cssSafe);
        }

        wp_register_style('resursbankabpaygw-pp-css-extra', false, [], '1.0.0');
        wp_enqueue_style('resursbankabpaygw-pp-css-extra');
        wp_add_inline_style(
            'resursbankabpaygw-pp-css-extra',
            esc_html(wp_strip_all_tags(self::getPartPaymentCssExtras()))
        );
    }

    /**
     * Enqueue styles related to ReadMore.
     */
    public static function enqueueReadMoreStyle(): void
    {
        try {
            WooCommerce::validateAndUpdatePartPaymentMethod();
            $readMoreCssSafe = (string) ((new ReadMoreCss())->content ?? '');
        } catch (Throwable $error) {
            Log::error(error: $error);
            $readMoreCssSafe = '';
        }

        wp_register_style('resursbankabpaygw-read-more-style', false, [], '1.0.0');
        wp_enqueue_style('resursbankabpaygw-read-more-style');

        if ($readMoreCssSafe === '') {
            return;
        }

        /*
         * Trusted SDK payload.
         * This content is generated by the Resurs Bank SDK as CSS and must remain valid CSS.
         * There is no general esc_*() helper for full stylesheet blocks in wp_add_inline_style().
         * safecss_filter_attr() is for style attributes, not full CSS blocks.
         */
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe CSS payload from trusted SDK, escaped at source by contract.
        wp_add_inline_style('resursbankabpaygw-read-more-style', esc_html(wp_strip_all_tags($readMoreCssSafe)));
    }

    /**
     * Enqueue scripts related to ReadMore.
     */
    public static function enqueueReadMoreJs(): void
    {
        if (is_product() && PartPayment::isEnabled()) {
            wp_register_script(
                'resursbankabpaygw-pp-readmore-js',
                '',
                ['wc-blocks-data-store'],
                '1.0.0',
                true
            );
            wp_enqueue_script('resursbankabpaygw-pp-readmore-js');

            $readMoreProductJsSafe = (string) (new ReadMoreJs(
                containerElDomPath: '#rb-pp-widget-container'
            ))->content;

            if ($readMoreProductJsSafe !== '') {
                /*
                 * Trusted SDK payload.
                 * This content is generated by the Resurs Bank SDK and must remain executable JS.
                 * It cannot be passed through esc_js() or wp_kses() without breaking the script.
                 * Per WordPress escaping guidance, this is treated as a safe prebuilt payload.
                 */
                // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe JS payload from trusted SDK, escaped at source by contract.
                wp_add_inline_script(
                    'resursbankabpaygw-pp-readmore-js',
                    $readMoreProductJsSafe
                );
            }
        }

        if (!is_checkout()) {
            return;
        }

        /*
         * Register a dedicated handle for checkout ReadMore so WooCommerce Blocks
         * can see that the inline payload belongs to a script with an explicit
         * wc-blocks-data-store dependency.
         */
        wp_register_script(
            'resursbankabpaygw-rm-readmore-js',
            '',
            ['wc-blocks-data-store'],
            '1.0.0',
            true
        );
        wp_enqueue_script('resursbankabpaygw-rm-readmore-js');

        $readMoreCheckoutJsSafe = (string) (new ReadMoreJs(containerElDomPath: 'body'))->content;

        if ($readMoreCheckoutJsSafe === '') {
            return;
        }

        /*
         * Trusted SDK payload.
         * This content is generated by the Resurs Bank SDK and must remain executable JS.
         * It cannot be passed through esc_js() or wp_kses() without breaking the script.
         * Per WordPress escaping guidance, this is treated as a safe prebuilt payload.
         */
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe JS payload from trusted SDK, escaped at source by contract.
        wp_add_inline_script(
            'resursbankabpaygw-rm-readmore-js',
            $readMoreCheckoutJsSafe
        );
    }

    /**
     * Enable all styles for the front end.
     *
     * @noinspection PhpArgumentWithoutNamedIdentifierInspection
     */
    public static function enqueueBasicGetAddressStyle(): void
    {
        try {
            wp_enqueue_style(
                'resursbankabpaygw-ga-basic-css',
                Route::getUrl('get-address-css'),
                [],
                '1.0.0'
            );
        } catch (Throwable $error) {
            Log::error(error: $error);
        }

        wp_enqueue_style(
            'resursbankabpaygw-ga-css',
            Url::getResourceUrl(
                module: 'GetAddress',
                file: 'custom.css',
                type: ResourceType::CSS
            ),
            [],
            '1.0.0'
        );
    }

    /**
     * Enable all scripts for the front end.
     *
     * @throws FilesystemException
     * @throws HttpException
     * @throws EmptyValueException
     * @throws IllegalValueException
     * @noinspection PhpArgumentWithoutNamedIdentifierInspection
     */
    public static function enqueueGetAddressJs(): void
    {
        /*
         * Main frontend asset.
         * This is the real script file and explicitly depends on wc-blocks-data-store.
         */
        wp_enqueue_script(
            'resursbankabpaygw-get-address',
            Url::getAssetUrl(file: 'update-address.js'),
            ['wp-data', 'jquery', 'wc-blocks-data-store'],
            WooCommerce::getAssetVersion(assetFile: 'update-address'),
            true
        );

        wp_localize_script(
            'resursbankabpaygw-get-address',
            'resursbankabpaygwFrontendData',
            [
                'currentCustomerType' => WcSession::getCustomerType(),
                'apiUrl' => Route::getUrl(
                    route: Route::ROUTE_SET_CUSTOMER_TYPE
                ),
                'getAddressEnabled' => EnableGetAddress::isEnabled(),
                'logLevel' => LogLevel::getData()->name,
                'isUsingCheckoutBlocks' => WooCommerce::isUsingBlocksCheckout()
            ]
        );

        $getAddressWidgetJsSafe = (string) GetAddress::getWidget()?->content;

        if ($getAddressWidgetJsSafe === '') {
            return;
        }

        /*
         * Register a dedicated handle for the inline SDK widget payload.
         * This avoids the WooCommerce Blocks warning about an inline or unknown
         * script accessing wc.wcBlocksData without a proper dependency declaration.
         */
        wp_register_script(
            'resursbankabpaygw-get-address-widget',
            '',
            ['resursbankabpaygw-get-address', 'wc-blocks-data-store'],
            WooCommerce::getAssetVersion(assetFile: 'update-address'),
            true
        );
        wp_enqueue_script('resursbankabpaygw-get-address-widget');

        /*
         * Trusted SDK payload.
         * This content is generated by the Resurs Bank SDK and must remain executable JS.
         * It cannot be passed through esc_js() or wp_kses() without breaking the script.
         * Per WordPress escaping guidance, this is treated as a safe prebuilt payload.
         */
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe JS payload from trusted SDK, escaped at source by contract.
        wp_add_inline_script(
            'resursbankabpaygw-get-address-widget',
            $getAddressWidgetJsSafe
        );
    }

    /**
     * Get the extra CSS for part payment.
     */
    private static function getPartPaymentCssExtras(): string
    {
        return ".rb-usp {\n" .
            "\tdisplay: block;\n" .
            "\tbackground-color: rgba(0, 155, 145, 0.8);\n" .
            "\tborder-radius: 4px;\n" .
            "\tpadding: 10px;\n" .
            "\tcolor: #fff;\n" .
            "\tmargin: 0 0 15px 0;\n" .
            "}\n" .
            ".rb-ps-cl-container {\n" .
            "\tmargin-bottom: 10px;\n" .
            "}\n";
    }
}