<h3><?php _e('Available payment methods', 'trbwc'); ?></h3>

<table width="100%" style="border: none;">
    <tr>
        <td width="25%" class="resursMethodHead"><?php _e('Method ID') ?></td>
        <td width="25%" class="resursMethodHead"><?php _e('Description') ?></td>
        <td width="25%" class="resursMethodHead"><?php _e('Amount limits') ?></td>
        <td width="25%" class="resursMethodHead"><?php _e('Method type') ?></td>
    </tr>
    <?php foreach ($paymentMethods as $methodObject) { ?>
        <tr>
            <td class="resursMethodBody"><?php echo $methodObject->id ?></td>
            <td class="resursMethodBody"><?php echo $methodObject->description ?></td>
            <td class="resursMethodBody"><?php echo $methodObject->type ?></td>
            <td class="resursMethodBody"><?php echo $methodObject->minLimit ?> - <?php echo $methodObject->maxLimit ?></td>
        </tr>
    <?php } ?>
</table>
