<?php
// Template
if (isset($customer_billing) && count($customer_billing)) {
    ?>
    <h3 class="resursOrderInfoTitle resursOrderInfoRow">
        <?php _e('Billing Address', 'resurs-bank-payments-for-woocommerce') ?>
    </h3>
    <div class="address resursOrderInfoRow">
        <?php
        // Sanitizing customer data.
        echo nl2br(esc_html(implode("\n", $customer_billing)));
        ?>
    </div>
    <?php
}
?>
