<h3>
    <?php

    use Resursbank\Ecommerce\Service\Merchant\Model\Method;
    use ResursBank\Module\Data;

    $extendView = (bool)Data::getResursOption('payment_methods_extended');

    _e(
        sprintf(
            'Available payment methods (Environment %s)',
            esc_html($environment)
        ),
        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
    ); ?></h3>

<?php
// $silentAnnuityException
// $silentGetPaymentMethodsException
?>
<?php if (!($exception instanceof Exception)) { ?>
    <div style="font-size: 14px; font-weight: bold !important; color: #000099 !important;"><?php _e(
            sprintf(
                'Payment Methods last update: %s',
                $lastMethodUpdate
            ),
            'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
        ); ?></div>

    <div class="paymentMethodsInfoBox">
        <div style="font-style: italic;margin-bottom: 5px;">
            <?php
            _e(
                'Amount limits: Defines from-to which order amount a payment method will be displayed in the checkout.',
                'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
            )
            ?><br>
            <?php
            _e(
                'Customer types: Which customers that can take advantage of a specific payment method (NATURAL: ' .
                'Private customers, LEGAL: Company based customers).',
                'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
            )
            ?>
        </div>
    </div>
    <table width="100%" style="border: none;">
        <tr>
            <td width="5%" class="resursMethodHead">
                <?php _e(
                    'Enabled Status',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
            <?php if ($extendView) { ?>
                <td width="10%" class="resursMethodHead"><?php _e(
                        'Method ID',
                        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                    ) ?></td>
            <?php } ?>
            <td width="35%" class="resursMethodHead"><?php _e(
                    'Name (No HTML)',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
            <?php if ($canUseFee) { ?>
                <td width="5%" class="resursMethodHead"><?php _e(
                        'Payment Fee',
                        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                    ) ?></td>
            <?php } ?>
            <td width="10%" class="resursMethodHead"><?php _e(
                    'Amount Limits',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
            <td width="10%" class="resursMethodHead"><?php _e(
                    'Customer types',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
            <td width="20%" class="resursMethodHead"><?php _e(
                    'Part payment options',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
        </tr>
        <?php
        if (is_array($paymentMethods) && count($paymentMethods)) {
            foreach ($paymentMethods as $methodObject) {
                ?>
                <tr>
                    <td class="resursMethodBody" id="td_rbenabled_<?php echo $methodObject->id ?>">
                        <input
                                id="rbenabled_<?php echo $methodObject->id ?>"
                                type="checkbox"
                                onchange="rbwcMethodState(this)"
                            <?php
                            try {
                                // Mark method enabled or disabled. Skip if not configured for some reason.
                                echo Data::isPaymentMethodEnabled($methodObject->id) ? 'checked="checked"' : '';
                            } catch (Exception $e) {
                                // Considered enabled on errors.
                                echo 'checked="checked"';
                            } ?>
                        >
                        <?php _e('Yes', 'tornevalls-resurs-bank-payment-gateway-for-woocommerce') ?>
                    </td>

                    <?php if ($extendView) { ?>
                        <td class="resursMethodBody">
                            <?php echo esc_html($methodObject->id); ?>
                        </td>
                    <?php } ?>
                    <td class="resursMethodBody">
                        <input class="trbwc_method_description_input"
                               id="method_description_<?php echo Data::getSanitizedKeyElement($methodObject->id) ?>"
                               type="text"
                               value="<?php echo esc_html($methodObject->name) ?>"
                               onchange="rbwcUpdateMethodDescription(this)"
                        >
                    </td>
                    <?php if ($canUseFee) { ?>
                        <td class="resursMethodBody">
                            <input class="trbwc_method_fee_input"
                                   id="method_fee_<?php echo Data::getSanitizedKeyElement($methodObject->id) ?>"
                                   type="text"
                                   size="4"
                                   value="<?php echo esc_html($methodObject->internalFee) ?>"
                                   onchange="rbwcUpdateMethodFee(this)"
                            >
                        </td>
                    <?php } ?>
                    <td class="resursMethodBody">
                        <div title="<?php _e(
                            'Amount limits (min - max).',
                            'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                        ); ?>" style="font-style: italic;">
                            <?php echo (float)$methodObject->minPurchaseLimit ?> - <?php echo (float)$methodObject->maxPurchaseLimit ?>
                        </div>
                    </td>
                    <td class="resursMethodBody">
                        <?php
                        $customerTypes = [];
                        // @todo Find out a better way to handle this.
                        if ($methodObject->enabledForLegalCustomer) {
                          $customerTypes[] = 'LEGAL';
                        }
                        if ($methodObject->enabledForNaturalCustomer) {
                          $customerTypes[] = 'NATURAL';
                        }
                        echo esc_html(implode(', ', $customerTypes));
                        ?>
                    </td>
                    <?php
                    $annuityClass = ($annuityEnabled === $methodObject->id) ? 'r_annuity_enabled' : 'r_annuity_disabled';
                    if ($methodObject->type !== 'REVOLVING_CREDIT') {
                        $annuityClass = 'r_annuity_idle';
                    } ?>
                    <td class="resursMethodBody <?php
                    echo esc_attr($annuityClass)
                    ?>"
                        id="r_annuity_field_<?php echo esc_attr($methodObject->id); ?>"
                    ><?php
                        if ($methodObject->type === 'REVOLVING_CREDIT' && isset($annuityFactors[$methodObject->id])) {
                            echo Data::getEscapedHtml($annuityFactors[$methodObject->id]);
                        } else {
                            if (!empty($annuityException) && $annuityException instanceof Exception) {
                                printf(
                                    __(
                                        'Received error from annuity factors request: %s (%d)',
                                        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                                    ),
                                    esc_html($annuityException->getMessage()),
                                    esc_html($annuityException->getCode())
                                );
                            }
                        } ?></td>
                </tr>
                <?php
            }
        } ?>
    </table>

    <?php
    if (!$canUseFee) {
        if (Data::isPaymentFeeAllowed()) {
            echo '<div style="color: #990000; font-width: bold;">';
            _e(
                'To be able to use fee settings, you have to change the plugin to work with ' .
                'the simplified or hosted shopflow.',
                'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
            );
            echo '</div>';
        }
    } else {
        echo '<div style="color: #009900; font-weight: bold;">';
        _e(
            'Fee settings: Allowed.',
            'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
        );
        echo '</div>';
    }
    ?>

<?php } else { ?>
    <div style="border: 1px solid darkred; padding: 5px; background: #EA9090FF; margin-bottom: 5px;">
        <?php echo esc_html($exception->getMessage()) ?> (Code <?php echo esc_html($exception->getCode()) ?>)
    </div>
<?php } ?>
