<?php

use ResursBank\Module\Data;

$useColumns = false;
if ((isset($short_id) && isset($columns[$short_id]) && (bool)$columns[$short_id])) {
$useColumns = true; ?>
<table class="form-table">
    <th scope="row" class="titledesc" style="border-right: 1px solid gray;" valign="top">
        <?php echo Data::getEscapedHtml($title) ?>
    </th>
    <td class="forminp forminp-checkbox" style="font-style: italic;" valign="top">
        <?php
        }
        ?>
        <button type="<?php echo esc_attr($action); ?>"
                class="button <?php echo esc_attr($class); ?>"
            <?php if (isset($id) && !empty($id)) { ?>
                id="button_<?php echo esc_attr($id); ?>"
                name="button_<?php echo esc_attr($id); ?>"
            <?php } ?>
            <?php
            // Protecting local onclick.
            echo wp_kses($custom_attributes, ['onclick' => []])
            ?>>
            <?php echo esc_attr($title) ?>
        </button>
        <?php
        if (!empty($desc)) {
            echo '<div>' . esc_html($desc) . '</div>';
        }
        ?>
        <?php if ($useColumns) { ?>
            <div id="div_<?php echo esc_attr($id); ?>"></div>
        <?php } else {
            ?>
            <span id="div_<?php echo esc_attr($id); ?>"></span>
            <?php
        } ?>

        <?php
        if ($useColumns) {
            echo '</td></table>';
        }
        ?>
