<h3>
    <?php use ResursBank\Module\Data;

    _e('Available callbacks', 'tornevalls-resurs-bank-payment-gateway-for-woocommerce');
    ?>
</h3>
<?php if (!($exception instanceof Exception)) { ?>
    <table width="100%" style="border: none;">
        <tr>
            <td width="20%" class="resursMethodHead"><?php _e(
                    'Callback',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
            <td width="80%" class="resursMethodHead"><?php _e(
                    'Callback URL',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                ) ?></td>
            <?php
            if ((bool)Data::getResursOption('show_developer')) {
                ?>
                <td width="80%" class="resursMethodHead"><?php _e(
                        'Remove',
                        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                    ) ?>
                </td>
                <?php
            }
            ?>
        </tr>
        <?php
        if (isset($callbacks) && is_array($callbacks)) {
            foreach ($callbacks as $callbackType => $callbackUrl) {
                ?>
                <tr id="callback_row_<?php echo sanitize_key($callbackType) ?>">
                    <td class="resursMethodBody"><?php echo sanitize_key($callbackType) ?></td>
                    <td class="resursMethodBody">
                        <input class="trbwc_cb_input"
                               value="<?php echo esc_url($callbackUrl) ?>"
                               readonly="readonly"></td>
                    <?php
                    if ((bool)Data::getResursOption('show_developer')) {
                        ?>
                        <td class="resursMethodBody" id="remove_cb_btn_<?php echo sanitize_key($callbackType); ?>">
                            <button type="button"
                                    onclick="doResursRemoveCallback('<?php echo sanitize_key($callbackType); ?>')">X
                            </button>
                        </td>
                        <?php
                    } ?>
                </tr>
                <?php
            }
        }
        ?>
    </table>
<?php } else { ?>
    <div style="border: 1px solid darkred; padding: 5px; background: #EA9090FF; margin-bottom: 5px;">
        <?php echo esc_html($exception->getMessage()) ?> (Code <?php echo esc_html($exception->getCode()) ?>)
    </div>
<?php } ?>
