<div id="r_annuity_p_<?php echo $id ?>">
    <select class="r_annuity" id="r_annuity_select_<?php echo $id ?>"
            onclick="setResursAnnuityClick(this, '<?php echo $id ?>', 'set')"
    >
        <?php echo $options ?>
    </select>
    <div id="r_activity_<?php echo $id ?>"></div>
</div>
<button id="r_annuity_button_<?php echo $id ?>" type="button"
        onclick="setResursAnnuityClick(this, '<?php echo $id ?>', 'click')"
>
<?php
    if (!$enabled) {
        _e('Enable', 'tornevalls-resurs-bank-payment-gateway-for-woocommerce');
    } else {
        _e('Disable', 'tornevalls-resurs-bank-payment-gateway-for-woocommerce');
    }
    ?></button><span id="r_activity_<?php echo $id ?>"></span>
