<!--
    For order info details we show a basic view with exception notification fields.
    If EComPHP triggers any exceptions they are shown here and then nowhere else.
 -->

<?php

use ResursBank\Module\Data;

$isDifferentAccount = false;

// If $ecom not present, something went wrong in the core functions of the plugin.
// Payments should be fully shown even if there is no payment.
if (isset($ecom)) {
    ?>
    <?php
    if (isset($ecomException['code']) && (int)$ecomException['code']) {
        ?>
        <span class="resursApiException">
        <?php
        $exceptionString = esc_html(sprintf('Exception %d: %s', $ecomException['code'], $ecomException['message']));
        // Error code 8 = Payment unexistent.
        // Error code 3 = Payment unexistent by REST.
        // Error code 404 = Well. It doesn't exist either.
        if (isset($ecom_short['rco_rejected_once']) && (in_array($ecomException['code'], [8, 3, 404], true))) {
            $errorString = __(
                'Payment could not be found at Resurs Bank. The metadata in the plugin however has ' .
                'been marked as a payment failure at least once during the initial process of the ' .
                'purchase. The customer in question may have been declined and then did not proceed. ' .
                'The purchase could also have failed by other reasons, like internal server errors ' .
                'at Resurs Bank.',
                'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
            );
            $exceptionString = '';
        }
        echo esc_html($errorString); ?><br>
            <br>
        <b><?php
            echo esc_html($exceptionString); ?>
        </b>
        </span>
        <?php
    } else {
        ?>
        <span>
                <?php
                if ($v2) { ?>
                    <span class="resursOrderInfoRow resursOrderInfoOldPluginNote">
                        <?php
                        echo strtoupper(
                            __(
                                'Not created with this plugin!',
                                'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                            )
                        ); ?>
                    </span>
                    <?php
                } ?>
            <table width="100%" class="r_payment_info_table">
            <tbody>
                <?php
                if (isset($ecom->isCurrentCredentials) && !$ecom->isCurrentCredentials) {
                    $isDifferentAccount = true; ?>
                    <span style="display:block;" class="resursOrderInfoDifferentCredentials">
<?php
printf(__(
    'Purchased with merchant username "%s" from environment "%s".',
    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
), esc_html($ecom->username), esc_html($ecom->environment)); ?>
            </span>
                    <?php
                } ?>
    </span>
        <?php
    } ?>

    <?php
    if (is_array($ecom_short) && count($ecom_short)) {
        $addExpanderAfter = 'paymentMethodType';
        $setExpander = false;
        $hasExpander = false;
        $allowExpander = false;
        foreach ($ecom_short as $key => $value) {
            // Only show ecom reference problems IF there was a problem.
            if ($key === 'ecom_had_reference_problems') {
                // Rename display key and translate it.
                $key = __(
                    'ECom Reference Error',
                    'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                );

                // Do not show this key if value is false.
                if ($value === false) {
                    continue;
                }
            }
            if ($setExpander && $allowExpander) {
                $hasExpander = true;
                $setExpander = false; ?>
                <button type="button"
                        class="button"
                        id="resurs_meta_expand_button"
                        onclick="resursToggleMetaData()"
                ><?php
                    _e(
                        'Expand metadata view',
                        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                    ); ?>
                </button>
                <?php
            }
            if (!empty($addExpanderAfter) && $key === $addExpanderAfter) {
                $setExpander = true;
            } ?>
            <tr class="resursOrderInfoRow">
                <th>
                    <?php echo strlen($key) > 2 ? esc_html(ucfirst($key)) : esc_html(strtoupper($key)) ?>
                </th>
                <td>
                    <?php
                    if ($key === 'paymentMethodInformation' && !empty($value)) {
                        // This data is stored for informative purpise in case merchants are changing credentials
                        // for an account with different payment methods available. It should therefore only show up
                        // if credentials has changed since this purchase.
                        if (!$isDifferentAccount) {
                            $value = __(
                                'Data will only be displayed if the purchase has been made with another merchant ' .
                                'account than the current in use.',
                                'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                            );
                        } else {
                            $jsonPayment = json_decode($value, true);
                            if (is_array($jsonPayment)) {
                                $newValue =
                                    __(
                                        'This data is shown to you since the purchase has been made with another ' .
                                        'merchant account than the current in use.',
                                        'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                                    ) .
                                    '<br><br>';
                                foreach ($jsonPayment as $methodKey => $methodValue) {
                                    if (is_string($methodValue)) {
                                        $newValue .= Data::getEscapedHtml(
                                            sprintf(
                                                '<div class="row"><b>%s</b>: %s</div>',
                                                $methodKey,
                                                $methodValue
                                            )
                                        );
                                    }
                                }
                                $value = sprintf(
                                    '<div class="container resursOrderInfoRow">%s</div>',
                                    esc_html($newValue)
                                );
                            }
                        }
                    }
                    if (is_numeric($value)) {
                        // sanitize_key is better to use than our own preg_replace.
                        echo
                        strtolower(
                            sprintf(
                                '<span id="rbwc_value_%s">%s</span>',
                                esc_attr($key),
                                esc_html($value)
                            )
                        );
                    } elseif (is_bool($value)) {
                        echo $value ? __('Yes.', 'tornevalls-resurs-bank-payment-gateway-for-woocommerce') : __(
                            'No.',
                            'tornevalls-resurs-bank-payment-gateway-for-woocommerce'
                        );
                    } elseif ($key === 'status') {
                        echo esc_html(implode(', ', (array)$value));
                    } elseif (is_string($value) && preg_match("/\n/", $value)) {
                        echo nl2br($value);
                    } elseif (is_array($value)) {
                        echo Data::getEscapedHtml(implode('<br>', $value));
                    } else {
                        echo esc_html($value);
                    } ?>
            </tr>
            <?php
        }

        if ($hasExpander) {
            ?>
            </td>
            <?php
        }
    } ?>

    </tbody>
    </table>

    <?php
}
?>
