<!--
    For order info details we show a basic view with exception notification fields.
    If EComPHP triggers any exceptions they are shown here and then nowhere else.
 -->
<?php
$isDifferentAccount = false;

// If $ecom not present, something went wrong in the core functions of the plugin.
// Payments should be fully shown even if there is no payment.
if (isset($ecom)) {
    ?>
    <p class="form-field form-field-wide">
        <label for="resurs_order_details" style="font-weight: bold;cursor: pointer" class="resursOrderInfoTitle">
            <?php
            _e('Order information and metadata for Resurs Bank', 'trbwc')
            ?>
        </label>
        <?php
        if (isset($ecomException['code']) && (int)$ecomException['code']) {
            ?>
            <span class="resursApiException">
        <?php
        $exceptionString = sprintf('Exception %d: %s', $ecomException['code'], $ecomException['message']);
        // Error code 8 = Payment unexistent.
        // Error code 3 = Payment unexistent by REST.
        // Error code 404 = Well. It doesn't exist either.
        if (isset($ecom_short['rco_rejected_once']) && (in_array($ecomException['code'], [8, 3, 404], true))) {
            $errorString = __(
                'Payment could not be found at Resurs Bank. The metadata in the plugin however has ' .
                'been marked as a payment failure at least once during the initial process of the ' .
                'purchase. The customer in question may have failed or been declined during the payment process ' .
                'and the did not proceed.',
                'trbwc'
            );
            $exceptionString = '';
        }
        echo $errorString; ?><br>
            <br>
        <b><?php
            echo $exceptionString; ?>
        </b>
        </span>
            <?php
        } else {
            ?>
            <span>
        <?php
        if (isset($ecom->isCurrentCredentials) && !$ecom->isCurrentCredentials) {
            $isDifferentAccount = true; ?>
            <span style="display:block;" class="resursOrderInfoDifferentCredentials">
<?php
printf(__(
    'Purchased with merchant username "%s" from environment "%s".',
    'trbwc'
), $ecom->username, $ecom->environment); ?>
            </span>
            <?php
        } ?>
    </span>
            <?php
        } ?>

        <?php
        if (is_array($ecom_short) && count($ecom_short)) {
            foreach ($ecom_short as $key => $value) {
                ?>
                <span style="display: block;" class="resursOrderInfoContainer">
                    <label for="resurs_order_<?php echo md5($key) ?>"
                           style="font-weight: bold;"><?php echo ucfirst($key) ?>
                    </label>
                    <?php
                    if ($key === 'paymentMethodInformation' && !empty($value)) {
                        // This data is stored for informative purpise in case merchants are changing credentials
                        // for an account with different payment methods available. It should therefore only show up
                        // if credentials has changed since this purchase.
                        if (!$isDifferentAccount) {
                            $value = __(
                                'This data is only displayed if the purchase has been made with another merchant ' .
                                'account than the current in use.',
                                'trbwc'
                            );
                        } else {
                            $jsonPayment = json_decode($value, true);
                            if (is_array($jsonPayment)) {
                                $newValue =
                                    __(
                                        'This data is shown to you since the purchase has been made with another ' .
                                        'merchant account than the current in use.',
                                        'trbwc'
                                    ) .
                                    '<br><br>';
                                foreach ($jsonPayment as $methodKey => $methodValue) {
                                    if (is_string($methodValue)) {
                                        $newValue .= sprintf(
                                            '<div class="row"><b>%s</b>: %s</div>',
                                            $methodKey,
                                            $methodValue
                                        );
                                    }
                                }
                                $value = sprintf('<div class="container resursOrderInfoContainer">%s</div>', $newValue);
                            }
                        }
                    }
                    if (is_numeric($value)) {
                        echo round($value, 2);
                    } elseif (is_bool($value)) {
                        echo $value ? __('Yes.', 'trbwc') : __('No.', 'trbwc');
                    } elseif ($key === 'status') {
                        echo implode(', ', (array)$value);
                    } else {
                        echo $value;
                    } ?>
                </span>
                <?php
            }
        } ?>

    </p>
    <?php
}
?>
