<!--
    For order info details we show a basic view with exception notification fields.
    If EComPHP triggers any exceptions they are shown here and then nowhere else.
 -->
<?php
// If $ecom not present, something went wrong in the core functions of the plugin.
// Payments should be fully shown even if there is no payment.
if (isset($ecom)) {
    ?>
    <p class="form-field form-field-wide">
        <label for="resurs_order_details" style="font-weight: bold;cursor: pointer" class="resursOrderInfoTitle">
            <?php
            _e('Order information and metadata for Resurs Bank', 'trbwc')
            ?>
        </label>
        <?php if (isset($ecomException['code']) && (int)$ecomException['code']) {
                ?>
            <span class="resursApiException">
        <?php echo $errorString; ?><br>
            <br>
        <b><?php printf('Exception %d: %s', $ecomException['code'], $ecomException['message']) ?></b>
        </span>
            <?php
            } else {
                ?>
            <span>
        <?php
        if (!$ecom->isCurrentCredentials) {
            ?>
            <span style="display:block;" class="resursOrderInfoDifferentCredentials">
<?php
printf(__(
    'Purchased with merchant username "%s" from environment "%s".',
    'trbwc'
), $ecom->username, $ecom->environment); ?>
            </span>
            <?php
        } ?>
    </span>
            <?php
            } ?>

        <?php
        if (is_array($ecom_short) && count($ecom_short)) {
            foreach ($ecom_short as $key => $value) {
                ?>
                <span style="display: block;" class="resursOrderInfoContainer">
                    <label for="resurs_order_<?php echo md5($key) ?>"
                           style="font-weight: bold;"><?php echo ucfirst($key) ?>
                    </label>
                    <?php
                    if (is_numeric($value)) {
                        echo round($value, 2);
                    } elseif (is_bool($value)) {
                        echo $value ? __('Yes.', 'trbwc') : __('No.', 'trbwc');
                    } elseif ($key === 'status') {
                        echo implode(', ', (array)$value);
                    } else {
                        echo $value;
                    } ?>
                </span>
                <?php
            }
        } ?>

    </p>
    <?php
}
?>
