<?php use ResursBank\Module\Data;

if ($get_address_form || $get_address_form_always) { ?>
    <span id="rbGetAddressFields">
    <div>
        <input type="radio"
               id="resursSsnCustomerTypeNatural"
               onclick="setResursGetAddressCustomerType(this)"
               name="resursSsnCustomerType"
               value="NATURAL"
               <?php
               echo $customer_type === 'NATURAL' ? 'checked=checked' : ''
               ?>
        > <?php echo esc_html($customer_private); ?>
        <input type="radio"
               id="resursSsnCustomerTypeLegal"
               onclick="setResursGetAddressCustomerType(this)"
               name="resursSsnCustomerType"
               value="LEGAL"
               <?php echo $customer_type === 'LEGAL' ? 'checked=checked' : '' ?>
        > <?php echo esc_html($customer_company); ?>
    </div>
    <div class="woocommerce-input-wrapper">
        <input
                class="input-text"
                type="text" size="32"
                id="resursSsnIdentification"
                onkeyup="setBillingInherit(this)"
                name="resursSsnIdentification">

        <?php
        if (Data::isExtendedTest()) {
            $customerCountry = strtoupper(Data::getCustomerCountry());
            //$customerCompany = Data::getCustomerCompanyName();
            $chosenCustomerType = Data::getCustomerType();
            if (isset($liveTestData[$customerCountry]['payments']['civicNumber']) &&
                is_array($liveTestData[$customerCountry]['payments']['civicNumber']) &&
                count($liveTestData[$customerCountry]['payments']['civicNumber'])
            ) {
                $civicNumberList = $liveTestData[$customerCountry]['payments']['civicNumber'];
                $civicNumberOptions = [];
                if (is_array($civicNumberList) && count($civicNumberList)) {
                    foreach ($civicNumberList as $civicType => $civicNumber) {
                        $isCompanyCivic = (bool)preg_match('/^company/i', $civicType);
                        if (($chosenCustomerType !== 'LEGAL' && $isCompanyCivic) ||
                            ($chosenCustomerType !== 'NATURAL' && !$isCompanyCivic)) {
                            continue;
                        }
                        $civicNumberOptions[] = sprintf(
                            '<option value="%s">%s (%s)</option>',
                            $civicNumber,
                            $civicType,
                            $civicNumber
                        );
                    }
                }
            }
            ?>
            <div class="woocommerce-input-wrapper" id="rbwc_extended_test_mode_helper">
                <select id="rbwc_civic_number_selector"
                        size="<?php echo count($civicNumberOptions) ?>"
                        onchange="rbwcSetCivicNumber(this)">
                    <?php
                    echo Data::getEscapedHtml(implode('', $civicNumberOptions));
                    ?>
                </select>
            </div>
            <?php
        }
        ?>

    </div>
    <div style="display: none;" class="resursGetAddressError"></div>
    <div id="resursGetAddressSpinnify" style="display: none;"></div>
    <?php
    if ($supported_country && $get_address_form) { ?>
        <div>
            <button id="rbGetResursAddressButton" onclick="getResursAddress();return false;"><?php echo esc_html($customer_button_text); ?></button>
        </div>
    <?php } ?>
</span>
<?php } ?>
