<span id="rbGetAddressFields">
    <div>
        <input type="radio"
               id="resursSsnCustomerTypeNatural"
               onclick="setResursGetAddressCustomerType(this)"
               name="resursSsnCustomerType"
               value="NATURAL"
               <?php
               echo $customer_type === 'NATURAL' ? 'checked=checked' : ''
               ?>
        > <?php echo $customer_private; ?>
        <input type="radio"
               id="resursSsnCustomerTypeLegal"
               onclick="setResursGetAddressCustomerType(this)"
               name="resursSsnCustomerType"
               value="LEGAL"
               <?php echo $customer_type === 'LEGAL' ? 'checked=checked' : '' ?>
        > <?php echo $customer_company; ?>
    </div>
    <div class="woocommerce-input-wrapper">
        <input
                class="input-text"
                type="text" size="32"
                id="resursSsnIdentification"
                onkeyup="setBillingInherit(this)"
                name="resursSsnIdentification">
    </div>
    <div style="display: none;" class="resursGetAddressError"></div>
    <div id="resursGetAddressSpinnify" style="display: none;"></div>
    <?php if ($supported_country) { ?>
        <div>
            <button onclick="getResursAddress();return false;"><?php echo $customer_button_text; ?></button>
        </div>
    <?php } ?>
</span>
