<?php use ResursBank\Gateway\ResursDefault;
use ResursBank\Module\Data;
if (!empty($customDescription)) { ?>
    <div>
        <?php
        echo Data::getEscapedHtml($customDescription);
        ?>
    </div>
<?php } ?>

<div class="resursReadMoreSpace">
    <?php if (ResursDefault::isInternalMethod($method)) { ?>
        <div
                type="button"
                class="btn btn-info active resursReadMoreButton"
                onclick="getRbReadMoreClicker('<?php echo esc_html($method->id) ?>', <?php echo (float)$total ?>)">
            <?php _e('Read more.', 'resurs-bank-payments-for-woocommerce') ?>
        </div>
    <?php } ?>
</div>
