<span id="rbGetAddressFields">
    <input type="radio" id="ssnCustomerType"
           onclick="setResursGetAddressCustomerType(this)"
           name="ssnCustomerType"
           value="NATURAL"> <?php echo $customer_private ;?>
    <input type="radio"
           id="ssnCustomerType"
           onclick="setResursGetAddressCustomerType(this)"
           name="ssnCustomerType"
           value="LEGAL">  <?php echo $customer_company ;?>
</span>