<div style="display:<?php echo !$streamLine ? $displayMode : ''; ?>">
    <label for="<?php echo $fieldName ?>" style="width:100%;display:block;">
        <?php echo $fieldLabel ?>
    </label>
    <input type="text"
           id="<?php echo sanitize_text_field($fieldName) ?>"
           size="<?php echo (int)$fieldSize ?>"
           class="field_<?php echo sanitize_text_field($fieldName) ?>"
           name="<?php echo sanitize_text_field($fieldName) ?>"
           onkeyup="setBillingInherit(this)"
           value="<?php echo sanitize_text_field($fieldValue) ?>">
</div>
