<?php

/**
 * Copyright © Resurs Bank AB. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

namespace Resursbankabpayments\Woocommerce\Modules\PaymentInformation;

use JsonException;
use ReflectionException;
use Resursbank\Ecom\Exception\ApiException;
use Resursbank\Ecom\Exception\AttributeCombinationException;
use Resursbank\Ecom\Exception\AuthException;
use Resursbank\Ecom\Exception\ConfigException;
use Resursbank\Ecom\Exception\CurlException;
use Resursbank\Ecom\Exception\FilesystemException;
use Resursbank\Ecom\Exception\Validation\EmptyValueException;
use Resursbank\Ecom\Exception\Validation\IllegalTypeException;
use Resursbank\Ecom\Exception\Validation\IllegalValueException;
use Resursbank\Ecom\Exception\ValidationException;
use Resursbank\Ecom\Module\Widget\PaymentInformation\Css as EcomPaymentInformationCss;
use Resursbank\Ecom\Module\Widget\PaymentInformation\Html as EcomPaymentInformation;
use Resursbankabpayments\Woocommerce\Util\Admin;

// Prevent direct access.
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Handles the output of the order view payment information widget
 *
 * @SuppressWarnings(PHPMD.CamelCaseVariableName)
 */
class PaymentInformation
{
    /**
     * Init method for loading module CSS.
     */
    public static function init(): void
    {
        add_action(
            'admin_head',
            'Resursbankabpayments\Woocommerce\Modules\PaymentInformation\PaymentInformation::setCss'
        );
    }

    public static function setCss(): void
    {
        if (!Admin::isInShopOrderEdit()) {
            return;
        }

        $paymentInformationCssSafe = (string) (new EcomPaymentInformationCss())->content;

        if ($paymentInformationCssSafe === '') {
            return;
        }

        /*
         * Trusted SDK payload.
         * This content is generated by the Resurs Bank SDK as CSS and must remain valid CSS.
         * There is no general esc_*() helper for full stylesheet blocks in this output context.
         * safecss_filter_attr() is intended for style attributes, not full CSS blocks.
         */
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Prebuilt safe CSS payload from trusted SDK, escaped at source by contract.
        echo '<style>' . esc_html(wp_strip_all_tags($paymentInformationCssSafe)) . '</style>';
    }

    /**
     * @throws JsonException
     * @throws ReflectionException
     * @throws ApiException
     * @throws AttributeCombinationException
     * @throws AuthException
     * @throws ConfigException
     * @throws CurlException
     * @throws FilesystemException
     * @throws ValidationException
     * @throws EmptyValueException
     * @throws IllegalTypeException
     * @throws IllegalValueException
     */
    public static function getWidgetHtml(string $paymentId): string
    {
        return (new EcomPaymentInformation(paymentId: $paymentId))->content;
    }
}
